const truth = [
    "Pernah suka sama seseorang? Berapa lama?",
    "Jika kamu bisa atau jika kamu mau, di gc mana atau luar gc yang ingin kamu berteman? (mungkin beda/jenis sama)",
    "Apa ketakutan terbesar kamu?",
    "Pernah suka sama seseorang dan merasa orang itu suka juga sama kamu?",
    "Siapa nama mantan pacar teman kamu yang diam-diam kamu suka?",
    "Pernah nyolong uang dari ayah atau ibu? Alasannya?",
    "Apa yang bikin kamu bahagia saat kamu sedih?",
    "Pernah naksir satu arah? Kalau iya, siapa? Gimana rasanya bro?",
    "Pernah jadi selingkuhan orang?",
    "Hal yang paling ditakuti",
    "Siapa orang yang paling berpengaruh dalam hidup kamu?",
    "Hal apa yang membanggakan yang kamu dapat tahun ini",
    "Siapa orang yang bisa bikin kamu keren?",
    "Siapa orang yang pernah bikin kamu sangat bahagia?",
    "Siapa yang paling mendekati tipe pasangan idealmu di sini?",
    "Siapa yang kamu suka main bareng?",
    "Pernah nolak orang? Alasannya kenapa?",
    "Sebutkan kejadian yang membuat kamu sakit hati yang masih kamu ingat",
    "Prestasi apa yang kamu dapat tahun ini?",
    "Kebiasaan terburuk kamu di sekolah apa?",
    "Lagu apa yang paling sering kamu nyanyikan di kamar mandi?",
    "Pernah punya pengalaman hampir mati?",
    "Kapan terakhir kali kamu benar-benar marah? Kenapa?",
    "Siapa orang terakhir yang menelepon kamu?",
    "Kamu punya bakat tersembunyi? Apa itu?",
    "Kata apa yang paling kamu benci?",
    "Apa video YouTube terakhir yang kamu tonton?",
    "Apa yang terakhir kamu cari di Google?",
    "Siapa di grup ini yang ingin kamu tukar hidupnya selama seminggu?",
    "Apa hal paling menakutkan yang pernah terjadi padamu?",
    "Pernah kentut dan menyalahkan orang lain?",
    "Kapan terakhir kali kamu membuat orang lain menangis?",
    "Pernah menghilangkan teman?",
    "Pernah lihat mayat?",
    "Anggota keluargamu yang paling mengganggu dan kenapa?",
    "Jika kamu harus menghapus satu aplikasi dari ponsel kamu, yang mana itu?",
    "Aplikasi apa yang paling banyak menyita waktu kamu?",
    "Pernah pura-pura sakit buat pulang dari sekolah?",
    "Barang paling memalukan di kamarmu apa?",
    "Apa lima barang yang akan kamu bawa jika terjebak di pulau terpencil?",
    "Pernah tertawa sampai ngompol?",
    "Kamu mencium bau kentutmu sendiri?",
    "Pernah ngompol di kasur saat tidur?",
    "Kesalahan terbesar yang pernah kamu buat apa?",
    "Pernah nyontek saat ujian?",
    "Hal terburuk yang pernah kamu lakukan apa?",
    "Kapan terakhir kali kamu menangis?",
    "Siapa yang kamu cintai paling banyak di antara orang tuamu?",
    "Kamu kadang-kadang masukin jari ke hidung?",
    "Siapa gebetanmu waktu sekolah?",
    "Jujur aja, kamu suka sama cowok di grup ini?",
    "Pernah suka sama seseorang? Berapa lama?",
    "Kamu punya pacar?",
    "Apa ketakutan terbesar kamu?",
    "Pernah suka sama seseorang dan merasa orang itu suka juga sama kamu?",
    "Siapa nama mantan pacar teman kamu yang dulu kamu suka diam-diam?",
    "Pernah nyolong uang dari ibu atau ayah?",
    "Apa yang bikin kamu bahagia saat kamu sedih?",
    "Kamu suka seseorang yang ada di grup ini? Kalau iya, siapa?",
    "Pernah dikhianati orang?",
    "Siapa orang yang paling penting dalam hidup kamu?",
    "Hal apa yang membanggakan yang kamu dapat tahun ini?",
    "Siapa orang yang bisa bikin kamu bahagia saat kamu sedih?",
    "Siapa orang yang pernah membuatmu merasa tidak nyaman?",
    "Pernah bohong sama orang tua?",
    "Masih suka sama mantan?",
    "Siapa yang kamu suka main bareng?",
    "Pernah nyolong barang besar? Alasannya?",
    "Sebutkan kejadian yang membuat kamu sakit hati yang masih kamu ingat",
    "Prestasi apa yang kamu dapat tahun ini?",
    "Kebiasaan terburuk kamu di sekolah apa?",
    "Kamu suka pembuat bot, Luhung? 🤣",
    "Pernah berpikir balas dendam sama guru?",
    "Kamu suka perdana menteri sekarang?",
    "Kamu non-veg atau veg?",
    "Jika bisa jadi tak terlihat, apa yang pertama kali akan kamu lakukan?",
    "Rahasia apa yang kamu simpan dari orang tua?",
    "Siapa gebetan rahasiamu?",
    "Siapa orang terakhir yang kamu kepoin di media sosial?",
    "Jika jin memberi tiga permintaan, apa yang akan kamu minta?",
    "Penyesalan terbesar kamu apa?",
    "Hewan apa yang paling mirip denganmu?",
    "Berapa banyak selfie yang kamu ambil sehari?",
    "Acara masa kecil favoritmu apa?",
    "Jika bisa jadi karakter fiksi sehari, siapa yang kamu pilih?",
    "Siapa yang paling sering kamu teks?",
    "Kebohongan terbesar yang pernah kamu bilang ke orang tua apa?",
    "Siapa selebriti yang kamu suka?",
    "Mimpi paling aneh yang pernah kamu alami apa?",
    "Kamu main PUBG? Kalau iya, kirim nomor ID-mu."
];

const dare = [
    "Makan 2 sendok makan nasi tanpa lauk, kalau seret bisa minum.",
    "Sebut orang yang bikin kamu terdiam.",
    "Telepon gebetan sekarang dan kirim screenshot.",
    "Cuma kirim emot di setiap pesan di grup/privat selama 1 hari.",
    "Ucapkan 'Selamat datang di Who Wants To Be a Millionaire!' di semua grup yang kamu punya.",
    "Telepon mantan dan bilang kangen.",
    "Nyanyikan bagian chorus dari lagu terakhir yang kamu putar.",
    "Kirim voice note ke mantan/gebetan/pacar, bilang 'Hai (nama), mau telepon sebentar. Aku kangen banget.'",
    "Pukul meja di rumah sampai dimarahi karena berisik.",
    "Bilang ke orang random, 'Aku baru dikasih tahu kalau kita kembar pertama, terus kita pisah, lalu aku operasi plastik. Dan ini yang paling ciyusss.'",
    "Sebut nama mantan.",
    "Buat 1 pantun untuk member!",
    "Kirim daftar chat WhatsApp kamu.",
    "Chat orang random dengan bahasa gaul, lalu kirim screenshot di sini.",
    "Ceritakan hal memalukan versi kamu sendiri.",
    "Tag orang yang kamu benci.",
    "Berpura-pura kesurupan, contoh: kesurupan anjing, kesurupan belalang, kesurupan kulkas, dll.",
    "Ganti nama jadi 'I AM DONKEY' selama 24 jam.",
    "Teriak 'ma chuda ma chuda ma chuda' di depan rumahmu.",
    "Posting foto pacar/gebetan.",
    "Ceritakan tipe pacar kamu!",
    "Bilang 'aku suka sama kamu, mau jadi pacarku?' ke lawan jenis yang terakhir kamu chat (kirim di wa/tele), tunggu balasannya, kalau sudah, kirim di sini.",
    "Rekam suara kamu membaca 'titar ke age do titar, titar ke piche do titar'.",
    "Prank chat mantan dan bilang 'aku cinta kamu, tolong kembali.' tanpa bilang itu dare!",
    "Chat kontak wa sesuai urutan baterai %, lalu bilang 'aku beruntung punya kamu!'",
    "Ganti nama jadi 'I am a child of randi' selama 5 jam.",
    "Ketik dalam bahasa Bengali selama 24 jam.",
    "Gunakan foto Selmon Bhoi selama 3 hari.",
    "Kirim kutipan lagu lalu tag member yang cocok dengan kutipan itu.",
    "Kirim voice note bilang boleh aku panggil kamu baby?",
    "Screenshot panggilan WhatsApp terbaru.",
    "Bilang 'YOU ARE SO BEAUTIFUL DON'T LIE' ke cowok!",
    "Panggil member grup secara personal, dan bilang fuck you.",
    "Berpura-pura jadi ayam di depan orang tua kamu.",
    "Ambil buku random dan baca satu halaman dengan keras di voice note lalu kirim di sini.",
    "Buka pintu depan dan melolong seperti serigala selama 10 detik.",
    "Ambil selfie memalukan dan tempel di foto profil kamu.",
    "Biarkan grup memilih kata dan lagu yang terkenal. Kamu harus nyanyikan lagu itu dan kirim di voice note.",
    "Jalan dengan siku dan lutut selama kamu bisa.",
    "Nyanyikan lagu kebangsaan di voice note.",
    "Breakdance selama 30 detik di ruang tamu.",
    "Ceritakan kisah paling sedih yang kamu tahu.",
    "Buat video twerk dance dan pasang di status selama 5 menit.",
    "Makan satu potong bawang putih mentah.",
    "Tunjukkan lima orang terakhir yang kamu kirim pesan dan apa yang mereka bilang.",
    "Pasang nama lengkap kamu di status selama 5 jam.",
    "Buat video tari pendek tanpa filter hanya dengan musik dan pasang di status selama 5 jam.",
    "Telepon sahabat kamu, panggil dia bitch.",
    "Pasang foto kamu tanpa filter di status selama 10 menit.",
    "Bilang aku cinta oli london di voice note.",
    "Kirim pesan ke mantan dan bilang aku masih suka kamu.",
    "Telepon gebetan/pacar/sahabat sekarang dan screenshot di sini.",
    "Panggil salah satu member grup secara personal dan bilang kamu jelek bustard.",
    "Bilang KAMU CANTIK/TAMPAN ke salah satu orang yang ada di puncak daftar pin kamu atau orang pertama di daftar chat kamu.",
    "Kirim voice note bilang boleh aku panggil kamu baby, kalau kamu cowok tag cewek/kamu cewek tag cowok.",
    "Tulis aku cinta kamu (nama member grup random, yang online) di chat pribadi, (kalau kamu cowok tulis nama cewek/kamu cewek tulis nama cowok) ambil foto dan kirim di sini.",
    "Gunakan foto aktor Bollywood sebagai foto profil kamu selama 3 hari.",
    "Pasang foto gebetan di status dengan caption, ini gebetan saya.",
    "Ganti nama jadi 'I AM GAY' selama 5 jam.",
    "Chat salah satu kontak di WhatsApp dan bilang aku akan jadi pacar kamu selama 5 jam.",
    "Kirim voice note bilang aku suka sama kamu, mau jadi pacarku atau ga? ke orang random dari grup (kalau kamu cewek pilih cowok, kalau cowok pilih cewek).",
    "Pukul pantatmu dengan keras dan kirim suara pukulan lewat voice note.",
    "Sebutkan tipe pacar kamu dan kirim fotonya di sini dengan caption, cewek/cowok terjelek di dunia.",
    "Teriak bravoooooo dan kirim di sini lewat voice note.",
    "Ambil foto wajah kamu dan kirim di sini.",
    "Pasang foto kamu dengan caption, aku lesbian.",
    "Teriak kata-kata kasar dan kirim di sini lewat voice note.",
    "Teriak kamu bajingan di depan ibumu/papamu.",
    "Ganti nama jadi aku idiot selama 24 jam.",
    "Tampar dirimu dengan keras dan kirim suara tamparan lewat voice note.",
    "Bilang aku cinta pemilik bot xeon lewat voice note.",
    "Kirim foto pacar kamu di sini.",
    "Buat video tantangan tari TikTok dan pasang di status, kamu bisa hapus setelah 5 jam.",
    "Putuskan persahabatan dengan sahabatmu selama 5 jam tanpa memberitahu itu dare.",
    "Bilang ke salah satu temanmu kalau kamu cinta dia dan mau menikah dengannya, tanpa memberitahu itu dare.",
    "Bilang aku cinta depak kalal lewat voice note.",
    "Tulis aku lagi horny dan pasang di status, kamu bisa hapus setelah 5 jam.",
    "Tulis aku lesbian dan pasang di status, kamu bisa hapus setelah 5 jam.",
    "Cium mamamu atau papamu dan bilang aku cinta kamu.",
    "Pasang nama ayahmu di status selama 5 jam.",
    "Kirim kata-kata kasar di grup mana saja kecuali grup ini, dan kirim bukti screenshot di sini."
];

let quotesis = ["Segala sesuatu telah Allah takdirkan. - QS. Al Qamar : 49", 
"Dan sesungguhnya DIA lah yang menjadikan orang tertawa dan menangis. - QS. An Najm: 43", 
"Janganlah kamu berduka cita, sesungguhnya Allah selalu bersama kita.- QS At-Taubah: 40", 
"Segala sesuatu telah Allah takdirkan. - QS. Al Qamar : 49", 
"Dan sesungguhnya DIA lah yang menjadikan orang tertawa dan menangis. - QS. An Najm: 43", 
"Janganlah kamu berduka cita, sesungguhnya Allah selalu bersama kita.- QS At-Taubah: 40", 
"Maka sesungguhnya bersama kesulitan itu ada kemudahan.QS Al Insyirah: 5", 
"Sesungguhnya Allah tidak akan mengubah keadaan suatu kaum hingga mereka merubah keadaan yang ada pada diri mereka sendiri. - Q.S. Ar Rad: 11", 
"Sesungguhnya Kami telah menciptakan manusia dalam bentuk yang sebaik-baiknya. - QS At- Tin: 4", 
"Dan Kami jadikan kamu berpasang-pasangan. - QS. An-Naba: 8", 
"Maka jangan sekali-kali membiarkan kehidupan dunia ini memperdayakan kamu. - QS. Fatir: 5", 
"Dan bersabarlah kamu, sesungguhnya janji Allah adalah benar. - QS. Ar-Rum: 60", 
"Dan barang siapa yang bertakwa kepada Allah, niscaya Allah menjadikan baginya kemudahan dalam urusannya. - Q.S At-Talaq: 4", 
"Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya. - QS. Al-Baqarah: 286", 
"Tidakkah dia menyadari bahwa sesungguhnya Allah melihat segala perbuatannya?. - QS. Al-Alaq: 14", 
"Bersabarlah wahai hati kelak akan ada seseorang yang datang dan siap menemani sisa hidupmu dalam ketaatan", 
"Diri kita sendiri yang bisa menentukan apakah cinta kita berbuah dosa ataukah berbuah pahala", 
"Dirimu yang sebenarnya adalah apa yang kamu lakukan di saat di ada orang yang melihatmu", 
"Janji Allah tak pernah mengecewakan, dan bila kamu masih meras kecewa mungkin ada yang salah dengan imanmu", 
"Rasa syukur tidak akan datang kepada orang yang tidak beriman dan tidak pernah kenyang", 
"Maafkan aku andai apa yang aku tulis dan aku share tentang ilmu agama tidak sesuai dengan coberku dan kehidupanku yang asli", 
"Kebanyakan manusia lebih senang menyalahkan orang lain daripada menyalahkan diri sendiri", 
"Biarlah orang melihat penampilah kita biasa, tetapi luar biasa di mata Allah", 
"Bersyukurlah bila dalam penantianmu, kau tetap gigih dalam kesendirian, sebab artinya kau telah memuliakan jalan Allah", 
"Malu akan sebuah masalah itu boleh tapi jangan berlebihan sebab jika kita Yakin Pertolongan Allah itu sangatlah nyata", 
"Yakinlah bahwa ada do’a yang terus dipanjatkan kepada Allah yang tidak putus-putus dari orang tua kita agar kita senantiasa menjadi anak yang sholeh dan sholehah", 
"Setiap hari aku berusaha semaksimal mungkin mencari rizki yang halal demi bisa menghalalkanmu", 
"Jatuh cinta bisa jadi sangat menyakitkan jika kita tidak mampu untuk mengendalikannya",
          // tambahkan quotes selanjutnya di sini
        ]

module.exports = { truth, dare, quotesis }